// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreatePrimaryUser(ctx context.Context, arg CreatePrimaryUserParams) (User, error)
	CreateSecondaryUser(ctx context.Context, arg CreateSecondaryUserParams) (User, error)
	FindUsersByEmailOrPhone(ctx context.Context, arg FindUsersByEmailOrPhoneParams) ([]User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUsersByPrimaryID(ctx context.Context, id int64) ([]User, error)
	UpdateUserToSecondary(ctx context.Context, arg UpdateUserToSecondaryParams) error
}

var _ Querier = (*Queries)(nil)
